From 7108eaa07bd031630489b41f8e072957fbfed7a8 Mon Sep 17 00:00:00 2001
From: Felix Yan <felixonmars@archlinux.org>
Date: Tue, 13 Oct 2015 22:41:23 +0800
Subject: [PATCH] Fix prints in namespace.py for Python 3.x compatibility

---
 python/planout/namespace.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/python/planout/namespace.py b/python/planout/namespace.py
index b5243fc..31ab927 100644
--- a/python/planout/namespace.py
+++ b/python/planout/namespace.py
@@ -116,11 +116,11 @@ def primary_unit(self, value):
     def add_experiment(self, name, exp_object, segments):
         num_avail = len(self.available_segments)
         if num_avail < segments:
-            print 'error: %s segments requested, only %s available.' % \
-                (segments, num_avail)
+            print('error: %s segments requested, only %s available.' %
+                  (segments, num_avail))
             return False
         if name in self.current_experiments:
-            print 'error: there is already an experiment called %s.' % name
+            print('error: there is already an experiment called %s.' % name)
             return False
 
         # randomly select the given number of segments from all available
@@ -140,7 +140,7 @@ def add_experiment(self, name, exp_object, segments):
 
     def remove_experiment(self, name):
         if name not in self.current_experiments:
-            print 'error: there is no experiment called %s.' % name
+            print('error: there is no experiment called %s.' % name)
             return False
 
         segments_to_free = \
